### ISSUE TITLE
Sorting / Searching remote samples

### ISSUE THREAD

**Issue by nicolasmroberts** [StraboSpot/Strabo-Micro#1]
The list of samples in a remote project is unsorted. Ideally it would be **1) sorted alphabetically by name** and **2) there would be a search bar at the top so you could just type the sample number in and it would live-filter the samples.** 

<img width="602" alt="Screen Shot 2021-01-14 at 10 54 47 AM" src="https://user-images.githubusercontent.com/35352527/104623403-f2c3e500-5657-11eb-8e51-a753a90f6049.png">

**Comment by jasonash** [comment]
@nicolasmroberts I have updated the sample selection form to show samples in alphabetical order, and also added a search box to further limit the samples shown.
<img width="712" alt="Screen Shot 2021-01-20 at 9 25 31 AM" src="https://user-images.githubusercontent.com/7904402/105196878-aff38880-5b01-11eb-920b-ef7a60977134.png">

Please try reinstalling (https://strabospot.org/micro) and let me know if this works.
