### ISSUE TITLE
Issue saving second sample reference micrograph

### ISSUE THREAD

**Issue by hannahcunning** [StraboSpot/Strabo-Micro#14]
I am getting an eternal save screen when I am saving after setting the scale for the second sample's reference micrograph. I am using the "add sample from Strabospot" option.

**Comment by jasonash** [comment]
Hi Hannah. Can you elaborate on which version of StraboMicro you are using? How large is your reference micrograph? Would it be possible to send me your images so that I can test? Thanks.

**Comment by jasonash** [comment]
Also, could you send me your latest log file? It should be located in your documents folder in the StraboMicroData folder.

**Comment by hannahcunning** [comment]
I am running 0.2.4, and the image is a tiff that is 60.2 MB. Do I need to convert the image to a jpeg? 
![ADA17A_XPL](https://user-images.githubusercontent.com/54119012/128921814-7f1c7887-effd-4475-b350-7a21a7f226b0.jpg)

[StraboMicroLog.txt](https://github.com/StraboSpot/Strabo-Micro/files/6964004/StraboMicroLog.txt)

**Comment by jasonash** [comment]
No, you don't need to convert the image to jpeg. Let me take a look at the log. I should be able to find a fix.

**Comment by jasonash** [comment]
Hi Hannah,

I think I might have fixed the issue. Here is a new version:

Windows: https://micro.strabospot.org/StraboMicro-0.2.5_hannah.exe
Mac: https://micro.strabospot.org/StraboMicro-0.2.5_hannah.pkg

Please note that you might need to uninstall before trying to install.

If the problem still isn't fixed, I'll need a copy of your .smz file saved  before your second micrograph is added.

Thanks,

Jason

**Comment by hannahcunning** [comment]
It is still not working, and i am having trouble uploading my .smz file. I have put it in a .zip file but it will still not attach.

**Comment by jasonash** [comment]
Hannah, you don't have to attach your .smz. You can just email it to me at jasonash@ku.edu. It might be best to use Dropbox or similar.

**Comment by jasonash** [comment]
Found bug in new Sample handler that was attempting to load image before it had been properly saved to disk. Hannah confirms fix.
