### ISSUE TITLE
Unable to save some data types

### ISSUE THREAD

**Issue by hannahcunning** [StraboSpot/Strabo-Micro#16]
I am having issues with adding some types of data to my micrographs due I think to my screen size. My laptop has a 14 in screen, and sometimes the button for "Save" for the Data Type popup is barely visible or not visible. 
![SM barely visible](https://user-images.githubusercontent.com/54119012/134696123-c78ea817-063a-475a-8d59-921fae58eeaf.jpg)
![SM not visible](https://user-images.githubusercontent.com/54119012/134696161-63ff7287-2eff-481f-8006-5ebc8cc83497.jpg)

When I try to resize the window it does not 'shrink' the window so that I can save the information, although it does make it able to hit the 'X' button to close the window, which is also often hidden. The data types where I am unable to save the data are: Fabric Info, Clastic Deformation Bands, Grain Boundary/Contact, Intragrain, Vein Info, and Pseudotachylite info.

**Comment by jasonash** [comment]
Screen size issues have been fixed. Closing.
