### ISSUE TITLE
new project and associated micrograph issues

### ISSUE THREAD

**Issue by blatchford-hannah** [StraboSpot/Strabo-Micro#17]
I’m working with the newest version of Strabo Micro. Here are three issues I’m running into:

1. when I create a new project, I get to the window in which I enter name, dates, collaborators, etc. I fill out every field, and when I click ‘next’, nothing happens. So I haven’t been able to create a new project that way

2. when I try to create a new project from field data, I can view my field projects, select one, but then I encounter seemingly the same issue where I can’t move past entering the basic details of a new dataset. I can make everything work if and only if I select a preexisting dataset in the field project.

3. I was able to start a project associated with field data, and upload a reference micrograph for each of my four samples, but I couldn’t upload any associated micrographs. I got to the point where I was ready to set the micrograph scale, but clicking ‘next’ didn’t do anything, regardless of the scaling option selected.

**Comment by jasonash** [comment]
This error was caused by some changes made to the new project routine. Problem has been resolved.
