### ISSUE TITLE
Issue installing StraboMicro 1.2.9

### ISSUE THREAD

**Issue by hannahcunning** [StraboSpot/Strabo-Micro#19]
I am trying to install StraboMicro 1.2.9 and I get a popup saying "Installation failed. Cannot load app info because the app.xml file could not be found". 
I am installing this on a new computer so I know it is not a cached data issue.

**Comment by jasonash** [comment]
Hi Hannah. Can you tell me if you are running Window or Mac?

**Comment by jasonash** [comment]
Hi Hannah. I did a little digging. It looks like this error can sometimes be caused by network issues, such as slow or unstable internet. I would suggest waiting a bit before trying to open the app. If that doesn't work, I would suggest trying the installer again.

**Comment by jasonash** [comment]
Hi Hannah. I did some more testing and I was able to reproduce the issue. I was able to fix the installer, but you'll have to download from this link: https://www.jdeploy.com/~strabomicro I apologize for the trouble.

**Comment by hannahcunning** [comment]
Thanks! It works now.

**Comment by jasonash** [comment]
Fixed according to Hannah.
