### ISSUE TITLE
Mis-placed overlays in left hand panel

### ISSUE THREAD

**Issue by noahjp-tamu** [StraboSpot/Strabo-Micro#2]
Overlay in left hand panel is sitting over the text, is placed properly in the image. Scaling/locating method was drag and stretch.
Does this for multiple images.

![MisplacedOverlay](https://user-images.githubusercontent.com/78372344/106489636-9b58ae00-647a-11eb-81a8-a857c6c9b133.jpg)

**Comment by jasonash** [comment]
@noahjp-tamu , Can you send me the .smz file to test? Thanks.

**Comment by noahjp-tamu** [comment]
Should be coming your way via email

**Comment by jasonash** [comment]
@noahjp-tamu I was able to recreate the issue. I'll continue to investigate. It should be an easy fix.

**Comment by jasonash** [comment]
@noahjp-tamu This issue should be fixed now. Please try reinstalling: https://strabospot.org/micro

**Comment by noahjp-tamu** [comment]
Yep, this is fixed now. Thanks!
