### ISSUE TITLE
Returning to folder?

### ISSUE THREAD

**Issue by noahjp-tamu** [StraboSpot/Strabo-Micro#3]
Not sure if this is possible or not, but when selecting images to upload, is it possible to return to the same folder that the previous image had been uploaded from (i.e. if the previous image was from C:/Work/Project/Photomicrographs/image1.jpg when browsing for a new photomicrograph could it open directly to the photomicrographs folder?)

**Comment by jasonash** [comment]
@noahjp-tamu I'm not sure that this is possible, but I'll do some digging. What's frustrating is that this is the expected behavior and it does this on Mac. I'll see what I can find.

**Comment by jasonash** [comment]
@noahjp-tamu OK, I spoke too soon. I think I have the "return to last folder" behavior working on windows now. Try reinstalling when you get a chance: https://strabospot.org/micro

**Comment by noahjp-tamu** [comment]
Awesome, this is fixed too. Thanks!
