### ISSUE TITLE
Minor suggestion: When changing between images "Loading..." instead of "Saving File..."

### ISSUE THREAD

**Issue by noahjp-tamu** [StraboSpot/Strabo-Micro#4]
When switching between images it says "Saving File..." which could be confusing. Suggest changing to "Loading..."

**Comment by jasonash** [comment]
@noahjp-tamu This must be a windows-specific issue. I will investigate.

**Comment by jasonash** [comment]
@noahjp-tamu  This should be fixed now. Please try reinstalling: https://strabospot.org/micro

**Comment by noahjp-tamu** [comment]
Resolved. Muchos gracias!
