### ISSUE TITLE
Overlays Issue

### ISSUE THREAD

**Issue by noahjp-tamu** [StraboSpot/Strabo-Micro#5]
If a layers visibility is turned off (eye closed) and the main window overlays are turned off and on again, the layer becomes visible but the eye still shows that it is closed. Opening the layers visibility (clicking on the eye) then turns it off (it becomes switched so on is off).
If the eye is off the layer should remain hidden when turning the main window overlays back on.

Hope that's clear, let me know if not.

**Comment by jasonash** [comment]
@noahjp-tamu  I can't seem to reproduce this error. Are you using windows or mac?

**Comment by noahjp-tamu** [comment]
Windows, I can show you at the meeting today

**Comment by jasonash** [comment]
@noahjp-tamu I just uploaded fresh binaries. Can you try re-installing to see if this issue persists? I've tried to reproduce the error on windows and mac, but I can't seem to make it happen. https://strabospot.org/micro

**Comment by jasonash** [comment]
We were unable to reproduce this issue. We will keep it open in case the issue arises again.
