### ISSUE TITLE
Associated micrograph automatically rotated 180 degrees

### ISSUE THREAD

**Issue by da-levy** [StraboSpot/Strabo-Micro#6]
Hi Strabo team,

I just downloaded StraboMicro and have been learning how it all works. I uploaded an associated micrograph to overlay on a reference micrograph. I was able to rotate and scale the image so it matched with the reference image. When I hit finish and I am taken back to the main Samples screen, the associated photomicrograph is flipped 180 degrees in the drop down menu (see attached).

Is there a way to rotate the photomicrograph in the associated micrograph editor page (second attachment)?

Thanks,
Drew
![Screenshot (25)](https://user-images.githubusercontent.com/68292240/108298857-7a6aab00-7152-11eb-8221-7face3e4d3cf.png)

![Screenshot (26)](https://user-images.githubusercontent.com/68292240/108299118-aede6700-7152-11eb-94fc-48a0f6640a88.png)

**Comment by jasonash** [comment]
Drew,
Right now, associated images are displayed in their native rotation as they were loaded into the StraboMicro app and only rotated to show their orientation in their parent. We have talked about trying to preserve the rotation in the detail view, but this leads to some pretty complicated and messy results when (for example) an image is rotated ~ 45°. If you would like your image to appear rotated, you could always rotate it before importing to StraboMicro. We'll continue to discuss with the community how they would like to proceed with this issue. Perhaps maintaining the rotation would be preferable.
