### ISSUE TITLE
Program freezes when too many files are uploaded?

### ISSUE THREAD

**Issue by da-levy** [StraboSpot/Strabo-Micro#8]
I am running into an issue where StraboMicro becomes very sluggish and gets stuck 'Loading image...' when I try to open an associated micrograph. I have 8 samples in my file. Each sample has a full thin section photomicrograph as the reference micrograph (each ~25 MB). In each sample, I am trying to upload ~20 associated micrographs (each ~3-4 MB). The current .smz file size is 598 MB. Currently, my project is frozen, and I cannot edit anything. I have tried closing and restarting the program several times, but it is still stuck. Do you have a recommendation for circumventing this issue?

**Comment by jasonash** [comment]
@da-levy Would it be possible for you to send me your .smz file for testing? You can send it via dropbox or similar to jasonash@ku.edu. Thanks.

**Comment by jasonash** [comment]
fixed with 0.2.4
